#!/usr/bin/env python3
#
#
# run with the command: sudo python probe_v2.py
# WORKS!
#

import os
import glob
import time
import RPi.GPIO as GPIO ## Import GPIO library

GPIO.setmode(GPIO.BOARD) ## Use board pin numbering
GPIO.setup(11, GPIO.OUT) ## Setup GPIO Pin 7 to OUT

os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')

base_dir = '/sys/bus/w1/devices/'
device_folder = glob.glob(base_dir + '28*')[0]
device_file = device_folder + '/w1_slave'

def read_temp_raw():
    f = open(device_file, 'r')
    lines = f.readlines()
    f.close()
    return lines

def read_temp():
    lines = read_temp_raw()
    while lines[0].strip()[-3:] != 'YES':
        time.sleep(0.2)
        lines = read_temp_raw()
    equals_pos = lines[1].find('t=')
    if equals_pos != -1:
        temp_string = lines[1][equals_pos+2:]
        temp_c = float(temp_string) / 1000.0
        temp_f = temp_c * 9.0 / 5.0 + 32.0
        #return temp_c, temp_f
        return temp_f
try:
		while True:
			print(read_temp())
			if read_temp() > 75:
				GPIO.output(11,True) ## Turn on GPIO pin 11
				time.sleep(300) # turns on for five minutes
				GPIO.output(11,False)
				time.sleep(300) # waits five minutes and repeats the temp evaluation

except KeyboardInterrupt:  
    # here you put any code you want to run before the program   
    # exits when you press CTRL+C 
		print "CTRL+C occurred!" 

finally:  
    GPIO.cleanup() # this ensures a clean exit and resets GPIO pins
